name: Generate cargo-sources.json

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git pipx
          pipx ensurepath
          pipx install poetry

      - name: Clone Impactor (upstream main)
        run: |
          git clone https://github.com/flatpak/flatpak-builder-tools.git
          git clone --depth 1 https://github.com/claration/Impactor.git app
          cd app

      - name: Install generator deps
        working-directory: flatpak-builder-tools/cargo
        run: |
          poetry install

      - name: Generate cargo-sources.json
        working-directory: flatpak-builder-tools/cargo
        run: |
          poetry run python3 flatpak-cargo-generator.py \
            $GITHUB_WORKSPACE/Cargo.toml \
            -o $GITHUB_WORKSPACE/cargo-sources.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        with:
          message: "Update cargo-sources.json"
          add: "cargo-sources.json"
          push: true